#!/bin/bash
set -e

rm -rf ./docs/autogenerated
mkdir ./docs/autogenerated

files=$(ls ./src | grep .js | xargs)

for f in $files; do
    echo "./src/$f -> ./docs/autogenerated/${f/.js/.md}"
    jsdoc2md ./src/$f &> ./docs/autogenerated/"${f/.js/.md}"
done
